apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "reserve"
  labels: 
    app: "reserve"
spec: 
  selector: 
    matchLabels: 
      app: "reserve"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "reserve"
    spec: 
      containers: 
        - 
          name: "reserve"
          image: "yh02195/reserve:00"
          ports: 
            - 
              containerPort: 8080

