apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "customercenter"
  labels: 
    app: "customercenter"
spec: 
  selector: 
    matchLabels: 
      app: "customercenter"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "customercenter"
    spec: 
      containers: 
        - 
          name: "customercenter"
          image: "yh02195/customercenter:00"
          ports: 
            - 
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          livenessProbe:
            httpGet:
              path: /getloglevel
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 5
