apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "car"
  labels: 
    app: "car"
spec: 
  selector: 
    matchLabels: 
      app: "car"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "car"
    spec: 
      containers: 
        - 
          name: "car"
          image: "yh02195/car:01"
          ports: 
            - 
              containerPort: 8080
          resources:
            requests:
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
